services:

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health/ping"]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0
      - DELIUS_ENABLED=false
      - NOMIS_ENDPOINT_URL=http://nomis-user-roles-api:8080
      - NOMIS_ENABLED=true

  nomis-user-roles-api:
    image: quay.io/hmpps/nomis-user-roles-api:latest
    container_name: nomis-user-roles-api
    networks:
      - hmpps
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - API_BASE_URL_OAUTH=http://hmpps-auth:8080/auth

  locations-inside-prison-api:
    image: quay.io/hmpps/hmpps-locations-inside-prison-api:latest
    container_name: locations-inside-prison-api
    networks:
      - hmpps
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - API_BASE_URL_OAUTH=http://hmpps-auth:8080/auth
      - SPRING_DATASOURCE_URL=jdbc:postgresql://locations-inside-prison-db:5432/locations_inside_prison?sslmode=prefer
      - HMPPS_SQS_LOCALSTACK_URL=http://localstack:4566

  localstack:
    image: localstack/localstack:3
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566:4566"
      - "8999:8080"
    environment:
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  locations-inside-prison-db:
    image: postgres
    networks:
      - hmpps
    container_name: locations-inside-prison-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=locations_inside_prison
      - POSTGRES_USER=locations_inside_prison
      - POSTGRES_DB=locations_inside_prison

  app:
    build:
      context: .
      args:
        BUILD_NUMBER: "1.0.0"
        GIT_REF: "a1b2c3"
        GIT_BRANCH: main
    networks:
      - hmpps
    ports:
      - "3000:3000"
    environment:
      - PRODUCT_ID=UNASSIGNED
      - REDIS_HOST=localhost
      - REDIS_ENABLED=false
      - HMPPS_AUTH_EXTERNAL_URL=http://localhost:9090/auth
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - MANAGE_USERS_API_URL=http://localhost:8080
      # These will need to match new creds in the seed auth service auth
      - API_CLIENT_ID=hmpps-locations-inside-prison
      - API_CLIENT_SECRET=clientsecret
      - SYSTEM_CLIENT_ID=hmpps-locations-inside-prison-system
      - SYSTEM_CLIENT_SECRET=clientsecret
      - SESSION_SECRET=somesecretvalue
      - TOKEN_VERIFICATION_API_URL=http://hmpps-auth:8080/auth
      - TOKEN_VERIFICATION_ENABLED=false
      - INGRESS_URL=http://localhost:3000

networks:
  hmpps:
