---
# Per environment values which override defaults in hmpps-locations-inside-prison/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: locations-inside-prison-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://locations-inside-prison-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    MANAGE_USERS_API_URL: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    COMPONENT_API_URL: "https://frontend-components-preprod.hmpps.service.justice.gov.uk"
    DPS_URL: "https://digital-preprod.prison.service.justice.gov.uk"
    LOCATIONS_API_URL: "https://locations-inside-prison-api-preprod.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"
    FLAG_MVP2_PERMANENT_DEACTIVATION: enabled
    FLAG_MANAGE_LOCATIONS_ENABLED: "false"
